library(targets)
library(tarchetypes)
library(extrafont)
library(tidyverse)
library(hrbrthemes)
library(ggalt)
library(DescTools)
library(patchwork)
library(janitor)
library(tidylog)
library(ca)
library(corrplot)
library(here)

# ggchicklet is not available from CRAN
# install.packages("ggchicklet", repos = "https://cinc.rud.is")
library(ggchicklet)
